EfProject/Controllers/CrudController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using EfProject.Models;

namespace EfProject.Controllers
{
    public class CrudController : Controller
    {
        static EF_TESTEntities db = new EF_TESTEntities();

        // GET
        public ActionResult Index()
        {
            var cliList = from c in db.Clientes select c;
            List<Cliente> clientes = new List<Cliente>();
            foreach (var item in cliList)
            {
                clientes.Add(Cliente.GetClienteObj(item));
            }

            return View(clientes);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Cliente cli)
        {
            if (!ModelState.IsValid) return View(cli);
            try
            {
                db.Clientes.Add(Cliente.GetClientesObj(cli));
                if (TryUpdateModel(db.Clientes))
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }

            return View(cli);
        }

        public ActionResult Delete(int id)
        {
            var cliente = db.Clientes.FirstOrDefault(c => c.ID == id);
            if (cliente == null)
            {
                return new HttpNotFoundResult(":'C");
            }

            return View(Cliente.GetClienteObj(cliente));
        }

        [HttpPost]
        public ActionResult Del(int id)
        {
            var cliente = db.Clientes.FirstOrDefault(c => c.ID == id);
            db.Clientes.Remove(cliente);
            db.SaveChanges();
            return Json(new {success=true,message="The row was deleted"});
        }

        public ActionResult Edit(int id)
        {
            var cliente = db.Clientes.FirstOrDefault(c => c.ID == id);
            return View(Cliente.GetClienteObj(cliente));
        }

        [HttpPost]
        public ActionResult Edit(Cliente cli)
        {
            if (!ModelState.IsValid) return View(cli);
            Clientes cliente = db.Clientes.Find(cli.ID);
            if (cliente != null)
            {
                cliente.nombre = cli.nombre;
                cliente.edad = cli.edad;
                cliente.fechaAlta = cli.fechaAlta;
                if (TryUpdateModel(cliente))
                {
                    db.Entry(cliente).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Edit", cliente);
        }
    }
}

EfProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/bundles/sweet")
    @Styles.Render("~/bundles/crud")
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        @Html.ActionLink("Application name", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse">
            <ul class="navbar-nav">
                <li class="nav-item">@Html.ActionLink("Home", "Index", "Crud", new {area = ""}, new {@class = "nav-link"})</li>
                <li class="nav-item">@Html.ActionLink("Information", "About", "Home", new {area = ""}, new {@class = "nav-link"})</li>
                <li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home", new {area = ""}, new {@class = "nav-link"})</li>
            </ul>
        </div>
    </div>
</nav>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.2019 - My ASP.NET Application</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/popper")
@Scripts.Render("~/bundles/popper-utils")
@Scripts.Render("~/bundles/crud")
@RenderSection("scripts", required: false)
</body>
</html>